### ISSUE TITLE
Nuget package 2.4.0 doesn't have .net core binaries

### ISSUE THREAD

**Issue by ninjaboy** [EasyPost/easypost-csharp#118]
We have recently tried to use official EasyPost nuget package, but there's something weird going on.
Although, according to the comments here: https://www.nuget.org/packages/EasyPost-Official/# the latest version of the package should have .net core support it seems like the distribution package itself doesn't have the necessary binaries. E.g. this is how the package restored on my machine looks like:

![image](https://user-images.githubusercontent.com/275925/44268685-26517980-a22a-11e8-830e-4857ab0c9234.png)

Also, since we are discussing .net core here, it would be really really nice if instead of .netcoreapp the library would be targeting .net standard. Is there any particular reason, why .netstandard cannot be targeted?

Thanks in advance.

**Comment by att14** [comment]
Since I do not maintain a production .Net application I was hoping the community would be able to help with .Net Core support. There is a large discussion in #49 about this. @MazdaRacerBoy may be able to help you with this since they have suggested that it is working for them.

If you are able to get this working I will accept any pull requests you make and try to have another contributor review it.
