### ISSUE TITLE
Invalid Cast while creating shipments

### ISSUE THREAD

**Issue by TGKN** [EasyPost/easypost-csharp#152]
Hi,
I have another error that regularly pops up in my application logs. Personally I was not able to reproduce it yet. Here is the stack trace:
System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JArray' to type 'System.String'. at EasyPost.Client.Execute[T](Request request) at EasyPost.Request.Execute[T]() at EasyPost.Shipment.SendCreate(Dictionary`2 parameters) at EasyPost.Shipment.Create()

Our customers did about 250 shipments just yesterday, this error came up 10 times.

Kai

**Comment by Justintime50** [comment]
@TGKN you mentioned not being able to reproduce this error, has this issue occurred again since initially bringing it up here? If so can you provide a code snippet/gist/link and the data you were sending?

**Comment by Justintime50** [comment]
Has this issue come up again since the initial reporting of it?

**Comment by nwithan8** [comment]
@TGKN it seems like there was an issue while deserializing the API's JSON response into an object (either a Shipment object or, since you say it only occurred a few times, an Error object after an API error). Unfortunately, we are unable to reproduce the error in our testing on our end, and without any sample data from you, we can't tell what property might be causing the issue (or if this issue has already been indirectly resolved since it was first reported).

Are you still running into this issue and/or could you provide more details, including:
- What shipment data is being sent to the API when this exception is thrown
- What version of the library you are using

Thank you in advance for your help.

**Comment by TGKN** [comment]
Hi,
As stated this error comes up irregularly and, of course, never came up in our development or staging system - only in production. Since we do not log all of our customers requests towards easypost in production (also due to data privacy) I can't really give you any further details on this one I am afraid.

**Comment by nwithan8** [comment]
@TGKN what version of the EasyPost library are you using that still produces this error?

**Comment by TGKN** [comment]
Hi,
I am not using any specific version. Due to the changes I had to make because of this (https://github.com/EasyPost/easypost-csharp/issues/98#issuecomment-1063302175) I am currently working on the tip revision fromfebruary last year...
Do you think updating to the latest revision will solve the issue? I saw you guys updated the Newtonsoft library....

**Comment by nwithan8** [comment]
> Hi, I am not using any specific version. Due to the changes I had to make because of this ([#98 (comment)](https://github.com/EasyPost/easypost-csharp/issues/98#issuecomment-1063302175)) I am currently working on the tip revision fromfebruary last year... Do you think updating to the latest revision will solve the issue? I saw you guys updated the Newtonsoft library....

We are working on a major v3.0.0 release soon, which I would advise updating to. I have been unable to reproduce the error in v3.0.0, so hopefully it has been indirectly fixed as part of our enhancements.

**Comment by nwithan8** [comment]
v3.0.0 is now out, please upgrade and try it out.
