### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by davitgr** [EasyPost/easypost-csharp#173]
@Justintime50 what is the ETA for the new release?

**Comment by Justintime50** [comment]
We are finalizing our internal build+release pipeline as we speak - I don't have a solid ETA but I'd hope we'll be able to cut a new version in the next month or so that will include all the landed items sitting on master that haven't yet been released (including SmartRate support and various bug fixes). Make sure to `watch` this project to keep an eye when we do release!

**Comment by davitgr** [comment]
@Justintime50 do you have any updates on when we can expect the new release to be?

**Comment by Justintime50** [comment]
Hey there, still no ETA; however, we are actively discussing our options as to the build system and release workflow. There are a lot of moving parts to get right and potentially a few more items to include prior to release. Thanks for checking back in, I'll make sure to update this thread when I have additional information.

**Comment by Justintime50** [comment]
Still no ETA; however, we are working to get this up and running (see https://github.com/EasyPost/easypost-csharp/pull/178 for example) and are hoping to release this soon.

**Comment by Justintime50** [comment]
Hey there, I'm happy to announce we've released `v2.6.0` which contains various updates including that update to RestSharp! You can download from Nuget here: https://www.nuget.org/packages/EasyPost-Official/
