### ISSUE TITLE
New RestSharp library

### ISSUE THREAD

**Issue by dolphinsd** [EasyPost/easypost-csharp#190]
If use latest restsharp, version 107, see https://restsharp.dev/v107/#restsharp-v107
and this library, it causes errors!
Method not found: 'RestSharp.IRestRequest RestSharp.RestRequest.AddHeader(System.String, System.String)'.

**Comment by Justintime50** [comment]
Thanks for reporting this! We also have an internal task for this issue and are actually looking into it now. We'll update you here when we have more info.

**Comment by Justintime50** [comment]
After digging into this a bit, RestSharp `v107` is not compatible with this library. We have plans in the coming couple weeks to upgrade to v107 in this library and make the necessary compatibility changes. We'll also be pinning RestSharp to 107 so that these breaking changes cannot happen again in the future when a new major version comes out.

My suggestion for now is to pin RestSharp to `v106` in your application until we've made the tweaks necessary in this library at which point you could upgrade.
