### ISSUE TITLE
3.1 Breaking Changes

### ISSUE THREAD

**Issue by declan-m** [EasyPost/easypost-csharp#270]
in 3.0 you use to be able to create your own classes of the api calls `new Address()`, `new Shipment()` etc. and before creation call `.AsDictionary();` at it would generate the right Dict for it. As of 3.1 this doesn't work.

```
Address toAddressData = new Address()
        {
            name = "",
            street1 = "",
            street2 = "",
            city = "",
            state = "",
            zip ="",
            country = "GB",
            company = "",
            phone = "",
            email = ""
        };
        toAddressData.AsDictionary();
```

The dictionary produces is really small and random

Example Console App. If you debug the variable `t` you will see it only contains the fields that are null
```
// See https://aka.ms/new-console-template for more information

using EasyPost;

Address toAddressData = new Address()
{
    name = "name",
    street1 = "line1",
    street2 = "street2",
    city = "city",
    state = "state",
    zip = "state",
    country = "GB",
    company = "tradername",
    phone = "phone",
    email = "email"
};
var t = toAddressData.AsDictionary();
Console.WriteLine("Hello, World!");
```

Why is `Dictionary<string, object?>` used everywhere? It makes code very unreadable and stops any IDE predictions of fields that can be used.

**Comment by nwithan8** [comment]
As of version 3.0.0, this is no longer the correct way of creating an Address. Instead, you need to pass in a dictionary of parameters to the `Address.Create()` method. Please refer to the upgrade guide entry [here](https://github.com/EasyPost/easypost-csharp/blob/master/UPGRADE_GUIDE.md#30-removes-non-static-create-functions).

**Comment by declan-m** [comment]
Why is it changing to Dictionaries for everything? It makes everything so unreadable having massive structs written in Dictionaries rather than using classes. You know exactly what variables exist within the API so it makes next to no sense to not use them.

**Comment by nwithan8** [comment]
In order to ensure that local objects are as synced as possible with server-side objects, we have structured the workflow in such a way that an end-user sends data to the API to create a server-side entry, and then receives a local copy of that server-side object, ensuring that data is created server-side first. As a result, we discourage end users from creating, i.e. an `Address` instance in any way other than through the `Address.Create()` function, which requires a dictionary of data as a parameter.

Currently, the client library is mostly a shim for API calls, with the end-user having to do most of the pre-call formatting. We ask users to pass in dictionaries/lists of formatted data that will be sent with little modification in HTTP calls.

To your point though, we are discussing improving the end-user experience by offloading some of these tasks. One In particular is instead asking users for typical individual parameters and handling the formatting internally, rather than requiring the end-user to do it.
