### ISSUE TITLE
Add bool verify and bool verify_strict properties to Address object

### ISSUE THREAD

**Issue by chadwixk** [EasyPost/easypost-csharp#402]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

The docs show these 2 `bool` parameters that are not currently part of the [Address object](https://github.com/EasyPost/easypost-csharp/blob/master/EasyPost/Models/API/Address.cs). Also, I've seen some other issues that show these aren't bool, but are values like `zip4` and `delivery`, so it is unclear what types and valid values they are to be.

<img width="548" alt="image" src="https://user-images.githubusercontent.com/5115308/215928284-9e95c899-3fa6-4f1f-a2c1-5611b2ed6000.png">

**Comment by nwithan8** [comment]
The `Address` object you linked to is the Address model created by the "create" request. This is different than the address creation parameters, which is where  `verify` and `verify_strict` are used.

**Comment by chadwixk** [comment]
We're actually using v3, so I linked to the wrong Address object.  Looks like [older version Address.cs v2](https://github.com/EasyPost/easypost-csharp/blob/v2/EasyPost/Address.cs) had it.

We create our [Address objects inline with shipment creation](https://www.easypost.com/docs/api/csharp#create-and-verify-addresses) to reduce api calls and increase performance for the user. 

And after we create the full `Shipment` object, we then make our first api call `client.CreateShipment(shipment)`.

The native api allows you to pass in these parameters in line with the address:
![image](https://user-images.githubusercontent.com/5115308/216175228-d2e55f04-1e53-4b54-8e2d-4d53dd489f8c.png)

Hence just asking for this same capability via this library as the native API supports it and it is more efficient (less api calls) and more performant for the user. Wouldn't EasyPost want to offer methods that lessen API calls and improve user experience?

Additionally, we try to stay away from using generic dictionaries and use the class objects to lessen errors, be able to find property references, etc. 

It just seems that this request only helps improve the library by lessening API calls (it would literally double the API calls to implement this way), improving end user experience (1 call is faster than 2) and enabling developers to reduce errors in code by using classes instead of string dictionaries.

**Comment by nwithan8** [comment]
As part of v3, we removed the ability to construct local objects. The only way to build an `Address` object would be via an API call (such as `myClient.Address.Create`), which will deserialize the response data into an `Address` object. This ensures that data is created on the server first, echoing back a read-only copy to you locally as an object.

As with the curl request screenshot above, you can include "verify" and "verify_strict" as parameters in the `myClient.Shipment.Create` function call to create/verify addresses in the same API call as creating a shipment. The parameters will need to exist in the same schema as the curl request data; the client library does little data mutation prior to making an API call, so the dictionary schema you provide as parameters will be passed along virtually unmodified.

We have heard [the concern](https://github.com/EasyPost/easypost-csharp/issues/380) about using dictionaries rather than classes to build parameters for the API calls, and are actively discussing ways to improve this logic.

**Comment by nwithan8** [comment]
First off, we'd like to apologize for hastily and prematurely closing this issue. It has since been reopened.

Thank you again for reporting this issue. We have a separate schema for creating an address than we have for the resulting `Address` resource. The `verify`/`verify_strict` parameters are arguments for creation, but aren't actually fields on the resulting `Address` itself. We need to get this better documented and still allow for taking advantage of classes instead of dictionaries. You are not the first to raise the concern about our dictionaries-for-parameter usage, and while we had originally added a task to address it to our backlog, it would appear this is a more pressing concern than we initially anticipated.

Internally, we have had preliminary discussions regarding the best way to improve this experience, and have prioritized implementing a solution for our next upcoming work cycle in a few weeks.

We are in the process of drafting a solution, something similar to the parameters mapping capabilities from the third-party EasyPost Extensions library, but wanted to incorporate feedback from our users in the process, to ensure the final solution we implement will be successful.

We will keep you updated here regarding our proposal in the coming days, and very much look forward to hearing your feedback.

As always, thank you for using EasyPost!

**Comment by nwithan8** [comment]
@chadwixk Just wanted to give you a heads up that we have begun working on the object parameters concept in #409 . We'd love for you to weigh in on the concept and let us know if this is something that will help you!

**Comment by chadwixk** [comment]
@nwithan8 I'm glad to hear the change in direction away from dictionaries! Thank you! I'll review more of #409 and try to provide feedback.

**Comment by nwithan8** [comment]
Hey @chadwixk , wanted to give you a heads up that we've released the object parameter concept in the [latest release ](https://github.com/EasyPost/easypost-csharp/releases/tag/v4.5.0). Hopefully the `Address.Create` parameter set will help with your specific issue.

I'm going to go ahead and close this ticket, but feel free to re-open it if anything else comes up!
