### ISSUE TITLE
[Bug]: Shipment Buy for FedEx Intl returns invalid shipment object

### ISSUE THREAD

**Issue by chadwixk** [EasyPost/easypost-csharp#403]
### Software Version

3.5

### Language Version

4.6.2

### Operating System

OS

### What happened?

1. Shipment Buy call for a shipment to Bosnia (BA) returns simply an error (as FedEx requires you to provide a signature which has not been done), not in the format of a Shipment object (which is expected) and hence throws an error when trying to serialize as a Shipment. 
2. Testing in Postman, the result comes back as the following, which is not a Shipment:
```
{
    "error": {
        "code": "SHIPMENT.INVALID_PARAMS",
        "message": [
            "Commercial invoice signature is required for US - BA shipment"
        ],
        "errors": []
    }
}
```

### What was expected?

A shipment object to be returned with an `ErrorObject` populated.

**Comment by nwithan8** [comment]
Thanks for reporting this, Chad! We're investigating this issue, but wanted to gather some more information from you.

We want to clarify if this is an API issue, or a client library issue. We're currently looking internally at the workflow/API aspect of this; namely, if the error you received is supposed to be thrown or not.

From a client library perspective, when an API call results in an error (a 4xx or 5xx status code), the client library should be able to handle it. For instance here, the API returns a 4xx status code saying the request was missing required parameters. The function you used, `myShipment.Buy()`, would normally return an updated `Shipment` object if the API call was successful, or deserialize the error JSON block you linked above from Postman into an `ApiError` exception (or one of its sub-types) and thrown it like a normal exception. We wanted to confirm that there wasn't an issue with the deserialization aspect here. When this API call fails, your application should throw an `ApiError` exception; is that what's happening here?

**Comment by Justintime50** [comment]
Hey @chadwixk,

If I'm understanding correctly, you are expecting a Shipment object to be returned when buying this shipment with an associated error message but instead are receiving an Error object, is that correct? If yes, this behavior is something that only happens when creating a shipment, or rating. When one attempts to rate a shipment, the Shipment object will be returned with an associated array of rating error messages for each carrier you rated against. This is helpful to know what changes may be necessary before purchasing a rate for a particular carrier.

In the case of buying a shipment, you would provide a carrier and service name or rate. Because there is no longer a matrix of carrier accounts, a single error is returned. The API returns an Error object which then gets deserialized in the library here as such because the shipment could not be bought.

What you are experiencing is the expected behavior of the API. Errors that occur when rating will be returned on a Shipment object like what I believe you are expecting to happen; however, when buying a shipment, a single Error object is returned instead. I hope this helps explain the behavior you came across. If you have additional questions about how the API works, we have an incredible support team that can be reached via support@easypost.com. If I misunderstood your question and indeed this is an error with the client library, please feel free to reopen this issue.
