### ISSUE TITLE
Shipment.Create() error when TLS 1.0 is disabled

### ISSUE THREAD

**Issue by delapohl** [EasyPost/easypost-csharp#73]
When we disable TLS 1.0 on our server, we get the following error when calling Shipment.Create():

```
System.NullReferenceException: Object reference not set to an instance of an object.  
at EasyPost.Resource.Merge(Object source)  
at EasyPost.Shipment.Create()  
``` 

Is there a dependency on TLS 1.0? We have no issues with it enabled.

**Comment by Roguelazer** [comment]
We support some TLS 1.0 clients (although it depends on your specific cipher suite configuration), and fully-support (and highly recommend) TLS 1.2. We do not support SSLv3 or older at all.

**Comment by delapohl** [comment]
Thanks for the quick response. To clarify, we do have TLS 1.0, 1.1 and 1.2 enabled (and SSL 2 and 3 disabled). We consistently get the above-captioned error if we disable TLS 1.0, leaving only TLS 1.1 and 1.2 enabled.

**Comment by Roguelazer** [comment]
What specific platform? Are you using GPO's or equivalent to change the cipher suite list?

**Comment by Roguelazer** [comment]
In particular, if your platform advertises TLS 1.2 with an ECDSA-compatible ECC Extension option but has all ECDSA-based cipher suites disabled, you can fail handshakes (since we'll offer you an ECDSA certificate, but we won't be able to negotiate a compatible cipher suite). This isn't technically a violation of the relevant RFC (4492), but it's sufficiently odd that it causes problems with most ECDSA+RSA dual-stack servers.

We've seen this issue from some clients (all using schannel under Windows), but haven't been able to determine which specific OS & configuration pair is to blame.

**Comment by delapohl** [comment]
We're on a Windows Server 2012 instance on GCP. We're using IIS Crypto to modify our registry to disable TLS 1.0, leaving the following:

# TLS 1.2 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	128
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	128
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d)	256
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c)	128
TLS_RSA_WITH_AES_256_CBC_SHA256 (0x3d)	256
TLS_RSA_WITH_AES_128_CBC_SHA256 (0x3c)	128
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)	256
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)	128
# TLS 1.1 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	128
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)	256
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)

**Comment by Roguelazer** [comment]
You'll note that your servers do support ECC cryptography (e.g., ECDHE for key distribution), but that all ECDSA cipher suites are disabled. `Schannel.dll` has shipped with working and default-enabled ECDSA support since Windows Server 2008/Vista ([ref](https://msdn.microsoft.com/en-us/library/ff468651.aspx)).

What are the values in the registry under `HKLM SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\CipherSuites`? I'm guessing that all of the ECDSA cipher suites have their DWORD value set to 0.

**Comment by delapohl** [comment]
Hm, `HKLM SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\CipherSuites` is empty.

**Comment by Roguelazer** [comment]
I've enabled a workaround that should force clients like yours to only use the RSA certificate. You should be able to to use TLS1.2 now.

I would still be interested to know what in your configuration is disabling ECDSA certificates, should you ever find out.

**Comment by delapohl** [comment]
Excellent, thanks! We'll test at our earliest opportunity.
